# Generated by Django 4.1.4 on 2022-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="files",
            options={
                "ordering": ("title",),
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
            },
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(upload_to="file/%Y/%m/%d/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="files",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название файла"),
        ),
    ]
