# Generated by Django 4.1.4 on 2022-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messages_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(verbose_name='Текст письма'),
        ),
    ]
